[project]
name = "ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.120.0",
    "numpy>=2.3.4",
    "pydantic>=2.12.3",
    "scikit-learn>=1.7.2",
    "uvicorn>=0.38.0",
]
